create or replace task APP_DB.APP_SCHEMA.LOAD_IMAGE_TAGS_TASK
	warehouse=COMPUTE_WH
	when system$stream_has_data('APP_DB.APP_SCHEMA.IMAGE_TAGS_RAW_STREAM')
	as CALL APP_DB.APP_SCHEMA.LOAD_AND_TRUNCATE_IMAGE_TAGS();