CREATE OR REPLACE PROCEDURE APP_DB.APP_SCHEMA.LOAD_AND_TRUNCATE_MAIN_IMAGES()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
    -- Insert data into MAIN_IMAGES table from MAIN_IMAGES_RAW
    INSERT INTO APP_DB.APP_SCHEMA.MAIN_IMAGES
    SELECT
        TRY_CAST(SRC:key:hotel_id::STRING AS NUMBER) AS HOTEL_ID,
        TRY_CAST(SRC:value:image_id::STRING AS NUMBER) AS IMAGE_ID,
        SRC:value:cdn_url::STRING AS CDN_URL
    FROM APP_DB.APP_SCHEMA.MAIN_IMAGES_RAW
    WHERE
        TRY_CAST(SRC:key:hotel_id::STRING AS NUMBER) IS NOT NULL
        AND TRY_CAST(SRC:value:image_id::STRING AS NUMBER) IS NOT NULL
        AND SRC:value:cdn_url::STRING IS NOT NULL;

    -- Truncate the MAIN_IMAGES_RAW table
    TRUNCATE TABLE APP_DB.APP_SCHEMA.MAIN_IMAGES_RAW;

    RETURN ''Data loaded into MAIN_IMAGES and MAIN_IMAGES_RAW truncated.'';
END;
';
