CREATE OR REPLACE PROCEDURE APP_DB.APP_SCHEMA.LOAD_AND_TRUNCATE_IMAGE_TAGS()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
    -- Insert data into IMAGE_TAGS table from IMAGE_TAGS_RAW
    INSERT INTO APP_DB.APP_SCHEMA.IMAGE_TAGS
    SELECT
        TRY_CAST(SRC:image_id::STRING AS NUMBER) AS IMAGE_ID,
        SRC:tags::ARRAY AS TAGS
    FROM APP_DB.APP_SCHEMA.IMAGE_TAGS_RAW
    WHERE TRY_CAST(SRC:image_id::STRING AS NUMBER) IS NOT NULL;

    -- Truncate the IMAGES_RAW table
    TRUNCATE TABLE APP_DB.APP_SCHEMA.IMAGE_TAGS_RAW;

    RETURN ''Data loaded into IMAGE_TAGS and IMAGE_TAGS_RAW truncated.'';
END;
';