CREATE OR REPLACE PROCEDURE APP_DB.APP_SCHEMA.LOAD_AND_TRUNCATE_IMAGES()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
    -- Insert data into IMAGES table from IMAGES_RAW
    INSERT INTO APP_DB.APP_SCHEMA.IMAGES
    SELECT
        TRY_CAST(SRC:hotel_id::STRING AS NUMBER) AS HOTEL_ID,
        TRY_CAST(SRC:image_id::STRING AS NUMBER) AS IMAGE_ID,
        SRC:cdn_url::STRING AS CDN_URL,
        TRY_CAST(SRC:height::STRING AS NUMBER) AS HEIGHT,
        TRY_CAST(SRC:width::STRING AS NUMBER) AS WIDTH,
        TRY_CAST(SRC:is_active::STRING AS BOOLEAN) AS IS_ACTIVE,
        TRY_CAST(SRC:created_at::STRING AS DATE) AS CREATED_AT,
        SRC:hash::STRING AS HASH
    FROM APP_DB.APP_SCHEMA.IMAGES_RAW
    WHERE
        TRY_CAST(SRC:hotel_id::STRING AS NUMBER) IS NOT NULL
        AND TRY_CAST(SRC:image_id::STRING AS NUMBER) IS NOT NULL
        AND SRC:cdn_url::STRING IS NOT NULL
        AND TRY_CAST(SRC:height::STRING AS NUMBER) IS NOT NULL
        AND TRY_CAST(SRC:width::STRING AS NUMBER) IS NOT NULL
        AND TRY_CAST(SRC:is_active::STRING AS BOOLEAN) IS NOT NULL
        AND TRY_CAST(SRC:created_at::STRING AS DATE) IS NOT NULL
        AND SRC:hash::STRING IS NOT NULL;

    -- Truncate the IMAGES_RAW table
    TRUNCATE TABLE APP_DB.APP_SCHEMA.IMAGES_RAW;

    RETURN ''Data loaded into IMAGES and IMAGES_RAW truncated.'';
END;
';