create or replace TABLE APP_DB.APP_SCHEMA.IMAGES_RAW (
	SRC VARIANT
);

create or replace TABLE APP_DB.APP_SCHEMA.IMAGES (
	HOTEL_ID NUMBER(38,0),
	IMAGE_ID NUMBER(38,0),
	CDN_URL VARCHAR(16777216),
	HEIGHT NUMBER(38,0),
	WIDTH NUMBER(38,0),
	IS_ACTIVE BOOLEAN,
	CREATED_AT DATE,
	HASH VARCHAR(16777216)
);

