create or replace TABLE APP_DB.APP_SCHEMA.MAIN_IMAGES_RAW (
	SRC VARIANT
);

create or replace TABLE APP_DB.APP_SCHEMA.MAIN_IMAGES (
	HOTEL_ID NUMBER(38,0),
	IMAGE_ID NUMBER(38,0),
	CDN_URL VARCHAR(16777216)
);