create or replace TABLE APP_DB.APP_SCHEMA.METRICS_TABLE (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	NUM_IMAGES_PROCESSED NUMBER(38,0),
	NUM_HOTELS_WITH_IMAGES NUMBER(38,0),
	NUM_MAIN_IMAGES NUMBER(38,0),
	NUM_NEW_MAIN_IMAGES NUMBER(38,0),
	NUM_UPDATED_MAIN_IMAGES NUMBER(38,0),
	NUM_DELETED_MAIN_IMAGES NUMBER(38,0),
	PROCESSED_AT TIMESTAMP_NTZ(9),
	primary key (ID)
);