CREATE STORAGE INTEGRATION APP_DB_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::339712703858:role/snow_role'
  STORAGE_ALLOWED_LOCATIONS = ('*');

CREATE STAGE APP_DB.APP_SCHEMA.APP_DB_STAGE
  STORAGE_INTEGRATION = APP_DB_INTEGRATION
  URL = 's3://app-db-datalake/inbound/'
  FILE_FORMAT = json_format;